FROM python:3.7

ENV PYLINT_PARAMS "--disable=fixme"

ADD . /cli_client/
RUN pip install /cli_client/
RUN pip install -r /cli_client/requirements-test.txt
CMD python -m pytest /cli_client/tests/ -v && pylint /cli_client/cli_client/ $PYLINT_PARAMS && pylint /cli_client/tests/*.py $PYLINT_PARAMS
